Codapalooza/Codapalooza/Controllers/GuidelinesController.cs
using System.Web.Mvc;

namespace Codapalooza.Controllers
{
	public class GuidelinesController : Controller
	{
		//
		// GET: /Guidelines/

		public ActionResult Index()
		{
			return View();
		}

	}
}

Codapalooza/Codapalooza/Controllers/ProjectController.cs
using System;
using System.Linq;
using System.Transactions;
using System.Web.Mvc;
using Codapalooza.Models;

namespace Codapalooza.Controllers
{
	public class ProjectController : Controller
	{
		private readonly CodapaloozaEntities _db;

		public ProjectController()
		{
			_db = new CodapaloozaEntities();
		}

		protected override void Dispose(bool disposing)
		{
			if (disposing)
				_db.Dispose();
		}

		public bool CanEdit { get; set; }

		//
		// GET: /Project/
		[Authorize(Roles = "Participant")]
		public ActionResult Index()
		{
			var projects = _db.Projects.OrderByDescending(p => p.Votes.Count).ToArray();
			foreach (var project in projects)
			{
				Validate(project);
			}
			return View(projects);
		}

		//
		// GET: /Project/Details/5

		public ActionResult Details(Guid id)
		{
			var project = _db.Projects.Single(p => p.Id == id);
			Validate(project);
			return View(project);
		}

		private void Validate(Project project)
		{
			project.CanEdit = User.Identity.Name.Equals(project.Proposer.UserName) ||
							  User.IsInRole("Admin");
		}

		//
		// GET: /Project/Create
		[Authorize(Roles = "Participant")]
		public ActionResult Create()
		{
			return View();
		}

		//
		// POST: /Project/Create

		[HttpPost]
		[Authorize(Roles = "Participant")]
		public ActionResult Create(Project project)
		{
			try
			{
				if (project.Id == Guid.Empty)
					project.Id = Guid.NewGuid();

				var participant =
				  _db.Participants.Single(
					p => p.UserName.Equals(User.Identity.Name, StringComparison.InvariantCultureIgnoreCase));
				project.ProposerId = participant.Id;
				_db.AddToProjects(project);
				_db.SaveChanges();

				return RedirectToAction("Index");
			}
			catch
			{
				return View(project);
			}
		}

		//
		// GET: /Project/Edit/5
		[Authorize(Roles = "Participant")]
		public ActionResult Edit(Guid id)
		{
			var project = _db.Projects.Single(p => p.Id == id);
			return View(project);
		}

		//
		// POST: /Project/Edit/5

		[HttpPost]
		[Authorize(Roles = "Participant")]
		public ActionResult Edit(Guid id, Project project)
		{
			try
			{
				var projectEntity = _db.Projects.Single(p => p.Id == id);
				UpdateModel(projectEntity);
				_db.SaveChanges();

				return RedirectToAction("Index");
			}
			catch
			{
				return View(project);
			}
		}

		//
		// GET: /Project/Delete/5
		[Authorize(Roles = "Participant")]
		public ActionResult Delete(Guid id)
		{
			var project = _db.Projects.Single(p => p.Id == id);
			Validate(project);
			return View(project);
		}

		//
		// POST: /Project/Delete/5

		[HttpPost]
		[Authorize(Roles = "Participant")]
		public ActionResult Delete(Guid id, Project project)
		{
			try
			{
				var projectEntity = _db.Projects.Single(p => p.Id == id);
				_db.DeleteObject(projectEntity);
				_db.SaveChanges();

				return RedirectToAction("Index");
			}
			catch
			{
				return View(project);
			}
		}

		[Authorize(Roles = "Participant")]
		public ActionResult Vote(Guid id)
		{
			try
			{
				var projectEntity = _db.Projects.Single(p => p.Id == id);
				var participantEntity = _db.Participants.Single(p => p.UserName == User.Identity.Name);

				var previousVotes = from v in _db.Votes
									where v.ParticipantId == participantEntity.Id
									select v;

				using (var transactionScope = new TransactionScope())
				{
					foreach (var previousVote in previousVotes)
					{
						_db.Votes.DeleteObject(previousVote);
					}

					Vote vote = new Vote()
					{
						Id = Guid.NewGuid(),
						ProjectId = projectEntity.Id,
						ParticipantId = participantEntity.Id
					};
					_db.Votes.AddObject(vote);
					_db.SaveChanges();

					transactionScope.Complete();
				}

				return RedirectToAction("Index");
			}
			catch
			{
				return RedirectToAction("Index");
			}
		}
	}
}

Codapalooza/Codapalooza/Controllers/ScheduleController.cs
using System.Web.Mvc;

namespace Codapalooza.Controllers
{
	public class ScheduleController : Controller
	{
		//
		// GET: /Schedule/

		public ActionResult Index()
		{
			return View();
		}

	}
}

Codapalooza/Codapalooza/Controllers/SponsorController.cs
using System.Web.Mvc;

namespace Codapalooza.Controllers
{
	public class SponsorController : Controller
	{
		//
		// GET: /Sponsor/

		public ActionResult Index()
		{
			return View();
		}

	}
}

Codapalooza/Codapalooza/Views/Shared/Copy of _Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.4.4.min.js")" type="text/javascript"></script>
</head>

<body>
    <div class="page">

        <div id="header">
            <div id="title">
                <h1>My MVC Application</h1>
            </div>

            <div id="logindisplay">
                @Html.Partial("_LogOnPartial")
            </div>

            <div id="menucontainer">

                <ul id="menu">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Participant", "Index", "Participant")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                </ul>

            </div>
        </div>

        <div id="main">
            @RenderBody()
            <div id="footer">
            </div>
        </div>
    </div>
</body>
</html>

Codapalooza/Codapalooza/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <link rel="SHORTCUT ICON" href="@Url.Content("~/favicon.ico")"/>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Codapalooza 2 - Programming Fest</title>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.4.4/jquery.min.js" type="text/javascript"></script>
  <script src="@Url.Content("~/js/codapalooza.js")" type="text/javascript"></script>
  <script type="text/javascript">
    $(function () {
      $('#tweets').tweetable({ username: 'codapalooza', time: true, limit: 15, replies: false });
      jQuery.preLoadImages("/imgs/multimedia-h.png", "/imgs/home-h.png", "/imgs/about-h.png", "/imgs/guidelines-h.png");
      $("#" + $.getSection()).addClass("selected")
    });
</script>
  <link href="@Url.Content("~/css/reset.css")" rel="stylesheet" type="text/css" />
  <link href="@Url.Content("~/css/codapalooza2.css")" rel="stylesheet" type="text/css" />
  @*<link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />*@
</head>
<body>
  <div id="menu">
    <div class="content">
      <ul>
        <li><a id="home" href="@Url.Action("Index", "Home")" class="logo">
          <img src="@Url.Content("~/imgs/codapalooza-logo.png")" width="131" height="26" /></a></li>
        @if (Context.User.IsInRole("Participant"))
        {
        <li><a id="project" href="@Url.Action("Index", "Project")">Projects</a></li>
        }
        <li><a id="guidelines" href="@Url.Action("Index", "Guidelines")">Lignes directrices</a></li>
        <li><a id="schedule" href="@Url.Action("Index", "Schedule")">Horaire</a></li>
        <li><a id="sponsor" href="@Url.Action("Index", "Sponsor")">Commanditaires</a></li>
        <li><a id="about" href="@Url.Action("Index", "About")">A propos</a></li>
        <li><span id="account">@Html.Partial("_LogOnPartial")</span></li>
        <li><div class="user">@Context.User.Identity.Name</div></li>
      </ul>
    </div>
  </div>
  <div id="header">
    <div class="content">
    @if (Request.Url.AbsolutePath.ToLower().StartsWith("home") || Request.Url.AbsolutePath == "/")
    {
      <img src="@Url.Content("~/imgs/codapalooza2.jpg")" width="960" height="379" />
    }
    else
    {
      <img src="@Url.Content("~/imgs/codapalooza2-small.jpg")" width="957" height="148" />
    }
    </div>
  </div>
  <div id="content">
    <div class="leftcol left">
      @RenderBody()
    </div>
    <div class="rightcol right">
      @if (Context.User.Identity.IsAuthenticated == false)
	  {
		  if (Codapalooza.Models.SubscriptionService.Current.RemainingPlaces() > 0)
		  {
	<a href="@Url.Action("Register", "Account")" class="inscription">inscrivez-vous</a>
			  if (Codapalooza.Models.SubscriptionService.Current.RemainingPlaces() == 1)
			  {
						<i>il ne reste qu'une place!</i>
			  }
			  else
			  {
						<i>il ne reste que @Codapalooza.Models.SubscriptionService.Current.RemainingPlaces() places</i>
			  }			
					
				
        <br />
        <br />
		  }
		  else
		  {
			<strong>Désoler, il ne reste plus de places!</strong>
		  }
	  }
	  else
	  {
		  Html.RenderAction("MustPay", "Home");
	  }
      <h2>
        Our recent tweets</h2>
      <div id="tweets">
      </div>
      <a href="http://pyxis-tech.com">
        <img src="@Url.Content("~/imgs/initiated-by-pyxis.png")" width="174" height="75" /></a>
      <br />
      <br />
      <a href="http://pyxis-tech.com/fr/notre-equipe?set_tag=equipe.Tarkeming">
        <img src="@Url.Content("~/imgs/tarkeming.png")" width="214" height="56" /></a>
    </div>
    <div class="clear">
    </div>
  </div>
</body>
</html>

Codapalooza/Codapalooza/Views/Shared/_LogOnPartial.cshtml
@if(Request.IsAuthenticated) {
    <text>@Html.ActionLink("Log Off", "LogOff", "Account")</text>
}
else {
    <text>@Html.ActionLink("Log On", "LogOn", "Account")</text>
}